version: "3.8"
services:
  nginx:
    container_name: nginx
    image: nginx:1.13
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - dhparam:/etc/ssl/certs   # <======
    networks:
      - app-network
  certbot:
    image: certbot/certbot
    depends_on:
      - nginx
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email pochta@test.by --agree-tos --no-eff-email --staging -d test.test.by -d www.test.test.by

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: movieService
    environment:
      - "SERVER_PORT=8080"
    expose:
      - "8080"
    depends_on:
        - nginx
    restart: always
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
      - 27070:27017
    restart: always
    networks:
      - app-network

volumes:
  certbot-etc:
  certbot-var:
  web-root:
  dhparam: # <======
    driver: local
    driver_opts:
      type: none
      device: C:\Users\krysh\IdeaProjects\movieService\dhparam
      o: bind

networks:
  app-network:
    driver: bridge